### ISSUE TITLE
Suggestions for TNP Limitless 7

### ISSUE THREAD

**Issue by Gbergz** [The-Nexus-Project/Limitless-7#1]
# Suggestions have moved!

---

### Got any suggestions?
Leave them in our discord channel under #mod-suggestions.

----

## Discord Invite: https://discord.gg/gwzpyQb

**Comment by GooseterV** [comment]
add some sort of a crafting calculator mod which can be used to calculate raw material cost for very complex nested recipes

**Comment by SirEdvin** [comment]
So, I have several CC:T addons to suggest:) 

First one is [UnlimitedPeripheralWorks](https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks). This mods adds a lot of custom integrations to exists minecraft blocks (such as rails, lectern, noteblock, etc) and also provides new cool peripheral and tools to play around:
- Peripheralium hub, that provide ability to install several upgrades to turtle/pocket computer
- Peripheral proxy, with ability to connect peripherals to computers without cables
- Integrations with mods, like AE2, Occultism, Nature's Compass, etc. 

Second one is [Turtlematic](https://www.curseforge.com/minecraft/mc-mods/turtlematic) - mod that mostly focused around idea to make turtle really capable of doing nearly everything, that player can. With this mod turtles can use custom items on blocks and entities, chisel blocks, perform smithing, brew potions and much more.

**Comment by BENZda** [comment]
Please add a Quest Book

**Comment by Gbergz** [comment]
@BENZda Whenever FTB Quests updates, quests will be added.

**Comment by BENZda** [comment]
> @BENZda Whenever FTB Quests updates, quests will be added.

Makes sense, but isn't there another Quest Mod ?

**Comment by Gbergz** [comment]
Nope, not one with that much depth and easy-to-make quests. Let's not continue the discussion here. Join discord if you wanna discuss further.

**Comment by TheOceanBreeze** [comment]
I would prioritize working on getting the mods from the previous version in the game.

**Comment by MokahTGS** [comment]
Theurgy - Magic/alchemy mod looks a lot like Thaumcraft 
https://www.curseforge.com/minecraft/mc-mods/theurgy

**Comment by JDDev0** [comment]
Energized Power - A technology mod with many machines
[https://legacy.curseforge.com/minecraft/mc-mods/energized-power](https://legacy.curseforge.com/minecraft/mc-mods/energized-power)
Energized Power was recently updated to v2.0.0.

**Comment by MSandro** [comment]
MineColonies
https://www.curseforge.com/minecraft/mc-mods/minecolonies

**Comment by EndangeredNayla** [comment]
aerial hell

**Comment by Koutsokou** [comment]
Ars Énergistique
https://www.curseforge.com/minecraft/mc-mods/ars-energistique

**Comment by EndangeredNayla** [comment]
> Energized Power - A technology mod with many machines
> [https://legacy.curseforge.com/minecraft/mc-mods/energized-power](https://legacy.curseforge.com/minecraft/mc-mods/energized-power)
> Energized Power was recently updated to v2.0.0.

Self promo

**Comment by DragonGold121** [comment]
Alex's Mobs
(I love this mod)
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

**Comment by ziumph** [comment]
Immersive engineering

**Comment by Jiudp** [comment]
Alex's Mobs, Alex's Caves, a touch of exploration

**Comment by TheOceanBreeze** [comment]
The Thermal Series was recently updated. Would be fun to see it come back to Limitless 7.

**Comment by Gbergz** [comment]
@TheOceanBreeze  Any major mod that was in Limitless 6 will eventually make its way to Limitless 7 too.

And Thermal Series is already on the list to be added next scheduled update. (v0.34.0)

**Comment by Gbergz** [comment]
# Suggestions have moved!

----

## Discord Invite: https://discord.gg/gwzpyQb
