### ISSUE TITLE
[Issue]: Ring missing in the quests

### ISSUE THREAD

**Issue by TackleToWin** [The-Nexus-Project/Limitless-7#101]
### What happened?

Not sure if it was intentional or not, but just noticed that the Ring of Water Walking is missing in the quests.

Noticed this on the official EU server

### Pack Version

Version: 1.2.0

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Intentional, same for Magnet Ring.
