### ISSUE TITLE
[Issue]: Server crash in v1.2.0 caused by ftb xmod compat

### ISSUE THREAD

**Issue by JulianVennen** [The-Nexus-Project/Limitless-7#102]
### What happened?

When you attempt to start the server it crashes with an error from FTB XMod Compat: https://mclo.gs/FXVVJJ3

### Pack Version

Version: v1.2.0

### To Reproduce

1. Download the server files
2. Instal forge
3. Run the server

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://mclo.gs/FXVVJJ3
```

**Comment by Gbergz** [comment]
Restart server, its uncommon and will be fixed in a near future update. Already reported to the FTB mod dev.

**Comment by Gbergz** [comment]
If you can't wait and want it fixed in your server now, use this jar file and replace the current one with it.
https://maven.ftb.dev/snapshots/dev/ftb/mods/ftb-xmod-compat-forge/2.1.1-SNAPSHOT/ftb-xmod-compat-forge-2.1.1-20240328.155215-1.jar
