### ISSUE TITLE
[Issue]: CobbleforDays Generators not showing up in JEI

### ISSUE THREAD

**Issue by TheShadowBudgie** [The-Nexus-Project/Limitless-7#108]
### What happened?

In JEI the CobbleforDays Cobblestone Generators are not showing up. 

### Pack Version

Version: 1.3

### To Reproduce

1. Boot up Game
2. Open Inventory
3. Search for "@Cobble*" or "cobble gen*

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

You can only see the recipes if you display the uses of e.g. Lava Bucket.

**Comment by Gbergz** [comment]
If I can reproduce this issue I will try to get it solved for next modpack update (v1.4.0)

**Comment by Gbergz** [comment]
fixed in v1.4.0
