### ISSUE TITLE
[Issue]: Elytra and Hang Glider are a bit bugy if you use it together

### ISSUE THREAD

**Issue by Xtremefear8519** [The-Nexus-Project/Limitless-7#111]
### What happened?

If you Fly with the Elytra and use the Hang Glider at the same time you can fly unlmited

### Pack Version

Version: 1.4.0

### To Reproduce

1. Grab a Elytra and a Hang Glider
2. Start flying with the Elytra
3. Use the Hang Glider in your Hand with right click
4. Fly unlimited (or until Elytra Breaks)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

More like a Bug then a real Issue, i just thought maybe you dont like something like that in your Modpack, i just want to let you know that :D
Have a Nice Day!

**Comment by Gbergz** [comment]
Not really a bug or an issue, intended by dev. 

Instead you can craft the reinforced hang glider which is Hang glider + elytra combined into one.
