### ISSUE TITLE
[Issue]: crash start server mohist 

### ISSUE THREAD

**Issue by ballou60** [The-Nexus-Project/Limitless-7#112]
crash start server mohist

Good morning,
I am contacting you following a conflict between your modpack and mohist

### Pack Version

Version: 1.4.0

### To Reproduce

the server crashes when I run it for the first time with any java

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
latest.log: https://pastebin.com/JMDiCrY7
debug.log: https://www.transferxl.com/fr/download/08jrhBQHJzDLcH
```

### Anything else to add?

the debug.log file is too big I will send it to you via XL transfer

**Comment by Gbergz** [comment]
Pack doesn't have support for Mohist in mind, but from what I do know Mohist runs on forge 47.2.20 and LL7 is on Forge 47.2.17.

Can't update forge as of now because that will break the pack.

**Comment by ballou60** [comment]
Ok thank you.
we opened it in vanilla version and JEI is not displayed in the menu
![image_2024-04-30_224850326](https://github.com/The-Nexus-Project/Limitless-7/assets/168589277/756adad6-964a-4283-a8c4-77817e4a46f6)
![jei bug](https://github.com/The-Nexus-Project/Limitless-7/assets/168589277/eb649e29-d8c2-4fc6-9344-81b0a0f820b7)

**Comment by Gbergz** [comment]
![ss](https://github.com/The-Nexus-Project/Limitless-7/assets/26634554/5b7025ee-a39a-435f-80f2-6c1ed25e0322)

**Comment by ballou60** [comment]
thank you very much guys
