### ISSUE TITLE
[Issue]: infinite dark oak wood glitch

### ISSUE THREAD

**Issue by TGNStudios** [The-Nexus-Project/Limitless-7#118]
### What happened?

If you craft 2 dark oak slabs together in a crafting table, it outputs an entire oak log instead of a plank.

### Pack Version

Version: 1.4.0

### To Reproduce

1. make dark oak slabs
2. put 2 in crafting table, on top of each other
3. profit (dark oak log is produced)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Update modpack. This is already fixed.
