### ISSUE TITLE
[Issue]: Custom FOV (customfov) has failed to load correctly

### ISSUE THREAD

**Issue by AzernoDev** [The-Nexus-Project/Limitless-7#126]
### What happened?

With docker-minecraft-server when i build container i have an error with custom FOV

### Pack Version

Version: 1.13.0 

### To Reproduce

1.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [x] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Relevant log output / crash report.

```shell
Forge: net.minecraftforge:47.3.1[07:32:29] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

	Custom FOV (customfov) has failed to load correctly

§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/Options for invalid dist DEDICATED_SERVER

]
```

**Comment by Gbergz** [comment]
Use the server files, Custom Fov isn't included in the server pack as it is a client mod.
