### ISSUE TITLE
[Issue]: Comforts Mod -Rope and Nail

### ISSUE THREAD

**Issue by Nite-Hare** [The-Nexus-Project/Limitless-7#127]
### What happened?

The comforts mod is missing the rope and nail item and recipe to use the hammock.

### Pack Version

Version: 1.13.0

### To Reproduce

1.Look/search for rope and nail in JEI

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [X] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Cacn't reproduce this, but maybe it got fixed when I updated some mods. Closing for now.
