### ISSUE TITLE
[Issue]: crash on latest version

### ISSUE THREAD

**Issue by VaporeonScripts** [The-Nexus-Project/Limitless-7#129]
### What happened?

![image](https://github.com/user-attachments/assets/606d4490-a49f-4e36-a592-ddfabe892208)

### Pack Version

Version: .latest

### To Reproduce

1.install it
crash

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [X] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
a
```

### Anything else to add?

a

**Comment by Gbergz** [comment]
Reinstall the modpack as a fresh instance.

**Comment by VaporeonScripts** [comment]
i did, but ok

**Comment by Gbergz** [comment]
Well I can't reproduce this specific issue, and I didn't get any information, not even logs. So not much to go of.

**Comment by Gbergz** [comment]
Alright, goodbye.
