### ISSUE TITLE
[Issue]: Everything is black

### ISSUE THREAD

**Issue by andreyyy3** [The-Nexus-Project/Limitless-7#13]
### What happened?

A bug happened! I make a world and when I get in the world everything is black, I m talking about textures, dirt,gravel everything is just black and it s unplayable.

### Pack Version

Version: Last version of modpack: v0.21.0

### To Reproduce

1.Just make a world and everything is black.. I have AMD so idk if it s the same issue as the last time.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
It s not crashing, I can play but it s unplayable cuz it s everything black.
```

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-7/issues/7
