### ISSUE TITLE
[Issue]:NA Server is Down

### ISSUE THREAD

**Issue by Whuck71** [The-Nexus-Project/Limitless-7#132]
### What happened?

A bug happened! - Since yesterday

### Pack Version

Version:  1.17.0

### To Reproduce

1.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [ ] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Not the place for this.
