### ISSUE TITLE
[Issue]: Can't get water inside the reactor from Bigger Reactors.

### ISSUE THREAD

**Issue by darksite189** [The-Nexus-Project/Limitless-7#14]
### What happened?

A bug happened! I cant get water inside reactor from bigger reactors

### Pack Version

Version: 

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
You put water in it before construction.

**Comment by Gbergz** [comment]
As coolant.

**Comment by darksite189** [comment]
Still nothing it fills up only the reactor coolant port but not the reactor itself.

**Comment by Gbergz** [comment]
Yeah, its a coolant. Obviously

**Comment by darksite189** [comment]
I dont understand, Im trying to use the reactor for it to produce steam but i cant get water inside.
