### ISSUE TITLE
[Issue]: cant create server on LL7

### ISSUE THREAD

**Issue by DarkShadow012** [The-Nexus-Project/Limitless-7#15]
### What happened?

cant create server 

### Pack Version

Version: 0.21.0

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by DarkShadow012** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-7/files/12569958/latest.log)

**Comment by Gbergz** [comment]
I'll reply in discord.
