### ISSUE TITLE
[Issue]:  Quest redemption bug causing crash

### ISSUE THREAD

**Issue by NickatNightt** [The-Nexus-Project/Limitless-7#16]
### What happened?

When attempting to redeem a quest the game will freeze then crash. i just started the pack up & was trying to redeem the "getting wood" quest & i have crashed each time. It only happens on that specific quest reward as far as i know.

### Pack Version

Version: V0.22.0

### To Reproduce

1. Start new world
2. gather wood to complete the "getting wood" quest
3. open quest book & open the "Minecraft" category
4. Click on the "getting wood" quest to redeem
5. Crash

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Registry Object not present: skinnedlanterns:pufferfish_lantern_block
```

**Comment by Gbergz** [comment]
Thanks for the report.

However. I can't reproduce this issue.
