### ISSUE TITLE
[Issue]: Enchanting Infuser + Apotheosis interaction is not working.

### ISSUE THREAD

**Issue by h1deto** [The-Nexus-Project/Limitless-7#17]
### What happened?

The Enchanting Infuser mod adds two new enchanters; "Enchanting Infuser" and "Advanced Enchanting Infuser".

The mod is supposed to have compability with the bookshelves from the mod "Apotheosis".

That interaction does not work at all.

![Advanced Enchanting Infuser with regular bookshelves](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/92f042ab-23fe-4578-9ee1-35e51e2961e7)
![Advanced Enchanting Infuser with regular bookshelves showing eterna](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/03984fe8-923a-4f45-b83d-86e50ce5dcdb)
![Enchanting Infuser with regular bookshelves](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/453a7e6b-8eaa-498e-b3b1-ccb3d51a50e4)
![Enchanting Infuser with regular bookshelves showing eterna](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/bf78637e-10aa-4e5a-a2e0-1dfe91b3447d)

---

There is one each of the bookshelves from Apotheosis to show that none of them work.

![Enchanting Infuser with one of each Apotheosis bookshelf](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/9d9dad37-829b-48ac-809b-b69e3abb6eda)
![Enchanting Infuser with one of each Apotheosis bookshelf showing no eterna](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/7b50683b-30d0-43e5-a0d0-24d01102b780)
![Advanced Enchanting Infuser with one of each Apotheosis bookshelf](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/4808f77d-8711-4a9a-bb30-4e250131b46b)
![Advanced Enchanting Infuser with one of each Apotheosis bookshelf showing no eterna](https://github.com/The-Nexus-Project/Limitless-7/assets/145142905/25e2c320-04aa-4991-ba0c-c89b8274bc66)

### Pack Version

Version: 0.22.0

### To Reproduce

1. Put Apotheosis bookshelves around an Enchanting infuser or Advanced Enchanting Infuser.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Report this to Enchanting Infuser dev.

**Comment by Gbergz** [comment]
https://github.com/Fuzss/enchantinginfuser/issues

And seems it already is, look at their issue #57

**Comment by h1deto** [comment]
My bad, thought something was setup wrong in the modpack since both mods work on their own, just not together.
