### ISSUE TITLE
[Issue]: EMI doesn't show the missing items required in Refined Storage crafting UI

### ISSUE THREAD

**Issue by Aeoniian** [The-Nexus-Project/Limitless-7#18]
### What happened?

Title explains

### Pack Version

Version: 0.22.0 - (Beta)

### To Reproduce

1. Make a Refined Storage set-up
2. Pick a recipe you know you don't have the materials for
3. EMI shows fill ingredients even though you don't have the materials to craft it 

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
N/A
```

### Anything else to add?

<img width="490" alt="image" src="https://github.com/The-Nexus-Project/Limitless-7/assets/145223972/630d13de-12a4-40ae-96e0-e79270067039">

^
in a normal crafting table

<img width="364" alt="image" src="https://github.com/The-Nexus-Project/Limitless-7/assets/145223972/1d1a4a93-16a4-4a9b-b798-f22bc288d563">

^
in refined storage UI crafting grid

**Comment by Gbergz** [comment]
Not something I can fix on my own I'm afraid, report either to EMI devs or Refined Storage devs.
