### ISSUE TITLE
[Issue]:  cant do mass search in the main search while in creative

### ISSUE THREAD

**Issue by adehart4875** [The-Nexus-Project/Limitless-7#20]
### What happened?

A bug happened! dosnt do anything is blank in the UI

### Pack Version

Version: 1.20.1 forge: 47.1.3

### To Reproduce

1. go into creative and go to mass search type in search and no items show

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Known issue, can't be fixed right now. Thanks for report!
