### ISSUE TITLE
[Issue]: Can not use Flight totem or charm to fly 

### ISSUE THREAD

**Issue by Samical** [The-Nexus-Project/Limitless-7#23]
### What happened?

On the 0.24.0 version of the pack.  Flight has been disabled with the Flight charm, and flight totem - have tried in a single player to make sure it was not server settings effecting it. The potion effect shows up on the player in their inventory but it does not allow you to fly. 

### Pack Version

Version: 0.24.0

### To Reproduce

1.start up a game and put on a flight charm or totem 
2. Try to fly and can't 

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Fixed next update
