### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by xiCrystalx** [The-Nexus-Project/Limitless-7#28]
### What happened?

Game is crashing before main menu :/
[crash-2023-10-07_12.12.56-client.txt](https://github.com/The-Nexus-Project/Limitless-7/files/12837449/crash-2023-10-07_12.12.56-client.txt)

### Pack Version

Version: 0.25.0

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Well, you're using Oculus v1.6.4. Remove it and replace it with this version specifically: https://legacy.curseforge.com/minecraft/mc-mods/oculus/files/4767500

**Comment by Gbergz** [comment]
Will solve it for you.

**Comment by xiCrystalx** [comment]
It works! thank u so much <3
