### ISSUE TITLE
[Issue]: EMI waiting for recipe data from server

### ISSUE THREAD

**Issue by MrElder** [The-Nexus-Project/Limitless-7#39]
### What happened?

In multiplayer, items are not displayed in EMI and it is impossible to view any recipes
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/42680756/43096e4f-5dbd-4ac6-8042-9c701b6be070)

### Pack Version

Version: 0.28.0

### To Reproduce

1. Join the multiplayer
2. Open Inventory or another container

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Never seen this before, but I would suggest restarting the game if not, then reinstall your game.

**Comment by Gbergz** [comment]
No idea then, wish I could say more. Try reinstalling the server, remove any extra mods added to the server. Transfer world to new server install.
