### ISSUE TITLE
sniffer and frogs

### ISSUE THREAD

**Issue by AwareFreak** [The-Nexus-Project/Limitless-7#4]
Hey the sniffer and the frogs don't work sniffer doesn't find any torch flower seeds and frogs don't lay any frog light with the sniffers I've waited easily 3 hours they don't do anything they don't move don't dig they just don't do anything I've tried it in other packs but everything works there

**Comment by Gbergz** [comment]
Known issue. Thanks for report though!

**Comment by Gbergz** [comment]
keep an eye on the issue here: `https://github.com/AbdElAziz333/Canary/issues/167`
