### ISSUE TITLE
Server Crashes on 0.29.0

### ISSUE THREAD

**Issue by willtarax** [The-Nexus-Project/Limitless-7#40]
Been having some issues trying to get the sever running. Was fine on 0.28.0 but when updating to 0.29.0 I get the following crash
[latest.log](https://github.com/The-Nexus-Project/Limitless-7/files/13275899/latest.log)

**Comment by Gbergz** [comment]
You have the wrong Forge Version installed.
You need 47.1.3.

`"Mod ID: 'forge', Requested by: 'rootsclassic', Expected range: '[47,47.1.3]', Actual version: '47.2.1'"`
