### ISSUE TITLE
when leaving or disbanding party (FTB) loose all quest progress  

### ISSUE THREAD

**Issue by ShadowRifter** [The-Nexus-Project/Limitless-7#41]
### What happened?

Hi there, just had an issue where i had to leave/disband my party through the ftb party manage, so i could unclaim my personal chunks and move them to the party chunks, after doing this i lost all my solo quest progression in the quest book and have to do it al again and get same rewards could also be used for duping rewards

### Pack Version

Version: 0.29.0

### To Reproduce

1. claim land undo solo player
2. join/create ftb party
3. do some quests from quest book 
4. leave party to unclaim personal claimed blocks (this is the point it loses all quest progression)
5. unclaim personal blocks 
6. join/create ftb party
7. reclaim all rewards again

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Anything else to add?

could be used to dupe rewards

**Comment by ShadowRifter** [comment]
Also just found out it has given me another 32 lvls after reclaiming rewards

**Comment by Gbergz** [comment]
This is intended.

**Comment by Gbergz** [comment]
Not an issue.

**Comment by ShadowRifter** [comment]
cheers for clarifying =)
