### ISSUE TITLE
[Issue]: Set Cyclic's configs to disable their antibeacon block due to it causing lag and deadlocks

### ISSUE THREAD

**Issue by TelepathicGrunt** [The-Nexus-Project/Limitless-7#42]
### What happened?

It is a known issue that Cyclic's code for their antibeacon block can cause lag when there's lots of entities with status effects on. In certain cases, it can also lock up the game permanently until restart due to running unsafely during worldgen. I made an issue report to Cyclic here
https://github.com/Lothrazar/Cyclic/issues/2269

I also made a PR to fix Cyclic here too but it is not merged yet:
https://github.com/Lothrazar/Cyclic/pull/2334

The temporary fix is to open Cyclic's config and set `potion_list` to `[]` and `harmful_potions` to `false`. This will disable the antibeacon code and give you better performance and stop Cyclic worldgen deadlocks.

### Pack Version

Version: 0.29.0

### To Reproduce

Teleport around in Bumblezone is likely going to be the easiest way to reproduce the issue. As soon as a mob from Bumblezone spawns in a structure with a status effect, Cyclic's code runs and deadlocks worldgen. Chunks will stop loading forever until restart.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Thanks for this, will get this done next update! Appreciated.

**Comment by TelepathicGrunt** [comment]
Cyclic released a jar with the optimization fix that will stop the deadlocks/lag regarding potion effects. Anti beacon feature can be reactivated safely in this version of cyclic
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/4976541
