### ISSUE TITLE
[Issue]: afrit crusher with iesnium ore give barrier block instead of iesnium dust

### ISSUE THREAD

**Issue by tomcool2002** [The-Nexus-Project/Limitless-7#44]
### What happened?

i made an afrit crusher to duplicate iesnium ore, but when feed iesnium ore, it give back barrier block. It give the right amount of item (I gave it 4 iesnium ore and it gave 16 barrier block so 4 for 1). It work just fine with diamond ore and emerald ore. I am playing in an older version but i didn't see this issue fixed in the update changelog. 

### Pack Version

Version: v0.28.0

### To Reproduce

1.summon an afrit crusher
2. drop iesnium ore
3. you get barrier block

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Update modpack, already fixed.
