### ISSUE TITLE
[Issue]: Java Ilegal exception

### ISSUE THREAD

**Issue by Ignaadex** [The-Nexus-Project/Limitless-7#53]
### What happened?

A bug happened!
![2023-12-16_09 10 05](https://github.com/The-Nexus-Project/Limitless-7/assets/100296517/26c506e1-9b94-4cda-bd0a-0b26ecabbf70)

### Pack Version

Version: v0.32.0

### To Reproduce

1. Sometimes middle click with the mouse in a chest or similar

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
This is caused by having apotheosis gems in your inventory upon sorting. Already reported and can't do much about it.

**Comment by Ignaadex** [comment]
Thanks for the answer still, love your pack🙏
Also there is a biome idk how it's called that crashes my game, it's full
of bamboo trees
