### ISSUE TITLE
[Issue]: Blazes do not drop loot

### ISSUE THREAD

**Issue by DOBBOTO** [The-Nexus-Project/Limitless-7#54]
### What happened?

A bug happened!
Blazes do not drop loot when spawnen with:
spawner
spawn eggs

also tried a new clean install to test it out

this occured while on a server and also singleplayer

### Pack Version

Version: 0.32.0

### To Reproduce

1.spawn a blaze with a spawner/spawn egg
2.kill it
3.you get nothing from it

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Already reported in discord, will probably be fixed in an upcoming update.
