### ISSUE TITLE
[Issue]: Hardened Integral Component 

### ISSUE THREAD

**Issue by GalaxyboyYTGH** [The-Nexus-Project/Limitless-7#58]
### What happened?

Hardened Integral Component doesn't have a recipe in JEI

### Pack Version

Version: 0.34.0

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Hey, it does. But it just doesn't show in JEI.

**Comment by Gbergz** [comment]
Fixed in 0.35
