### ISSUE TITLE
[Issue]: All Farmer's Delight food recipes that require the Cooking Pot are uncraftable.

### ISSUE THREAD

**Issue by ZephiraZ** [The-Nexus-Project/Limitless-7#59]
### What happened?

EMI displays "Empty Tag" as ingredients for all recipes using the Cooking Pot. Placing the normal ingredients for any food recipe into the Cooking Pot does nothing.

### Pack Version

Version: Limitless-7-0.34.0

### To Reproduce

1. Open EMI
2. Search for "@farmer"
3. View recipe for Ratatouille

![RatatouilleEMI](https://github.com/The-Nexus-Project/Limitless-7/assets/102687150/43098a6b-02d2-4294-8f7d-394dd0af7049)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Known issue, already reported. Do /reload or rejoin the world to temp fix.
