### ISSUE TITLE
[Issue]: Search Bar in creative doesnt show any blocks nor do they appear

### ISSUE THREAD

**Issue by FevilGitHub** [The-Nexus-Project/Limitless-7#6]
### What happened?

Hi! I decided to go into creative and noticed when i wanted to search something up, nothing was available for results or overall! Is this a bug or was this intentional?
![image](https://github.com/The-Nexus-Project/Limitless-7/assets/106572267/b4f52d6e-9aa9-4865-953e-da0409f347f6)

### Pack Version

Version: 1.15.0

### To Reproduce

1. Go into creative gamemode and then go to the search bar in the creative menu

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Known issue. Caused by EMI. Issue is already reported.

Can't fix it for now, but I will update this issue once solved.
