### ISSUE TITLE
[Issue]: Cyclic Gold Chain Uncraftable

### ISSUE THREAD

**Issue by ThatGamePerson** [The-Nexus-Project/Limitless-7#62]
### What happened?

Cyclic's gold chain recipe isn't in JEI. When using two gold nuggets and a gold ingot in a standard "chain" crafting recipe, you instead get 'Dustrial Decor's gold chains.

### Pack Version

Version: 0.35.0

### To Reproduce

1. Type "@cyclic gold chain" into JEI's search bar. Nothing will appear.

![no_cyclic_gold_chain_recipe](https://github.com/The-Nexus-Project/Limitless-7/assets/67931991/4fc445be-7627-4928-91df-0b7b9af88609)

2. In a crafting table, put a gold nugget, then a gold ingot, and then another gold nugget vertically. This will yield 'Dustrial Decor's gold chains, not Cyclic's. See image below.

![gold_chain_dustrial_decor](https://github.com/The-Nexus-Project/Limitless-7/assets/67931991/3f3e2af5-4fef-4e5e-8bb7-480936d2f137)

3. Type "unwitnessed" into JEI's search bar. Click on "Unwitnessed Amulet" from Enigmatic Legacy. Notice that the recipe requires four of Cyclic's gold chains.

![unwitnessed_amulet_recipe](https://github.com/The-Nexus-Project/Limitless-7/assets/67931991/63890404-d427-4cd4-b685-ff20ec8cdaa3)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Anything else to add?

This is a problem since the unwitnessed amulet from Enigmatic Legacy requires Cyclic's gold chains in its recipe, rendering it uncraftable.

**Comment by Gbergz** [comment]
Oversight when transfering over that specific recipe from Limitless 6, will have to adjust it for next hotfix or major update.

Thanks.

**Comment by ThatGamePerson** [comment]
Of course, no problem.
