### ISSUE TITLE
[Issue]: I am hosting server of LL7 and it crahsed

### ISSUE THREAD

**Issue by KillerzGodZ** [The-Nexus-Project/Limitless-7#63]
### What happened?

my friend was just going in a direction and just caused the server to crash 3 times without fail so I had to NBT'ed his Position to not make server crash. 

### Pack Version

Version: 0.35.0

### To Reproduce

1. Friend was just adventuring in overworld
2. Encounted a generating structure
3. caused the server to crash (piston in structure from look of things)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
https://mclo.gs/JFdFMGm | https://mclo.gs/TQIrGVV
```

### Anything else to add?

My friends that are adventuring encounted this problem twice now in two different locations of the overworld that seems to be caused by pistions in structure generation.

**Comment by Gbergz** [comment]
Fixed soon in a hotfix.

**Comment by KillerzGodZ** [comment]
> Fixed soon in a hotfix.

Thank you for repling back apprecite it.
