### ISSUE TITLE
2 [Issue]: crashing my game  i cant make a cow in the jar

### ISSUE THREAD

**Issue by Evilteen18** [The-Nexus-Project/Limitless-7#68]
### What happened?

mending crash and cow in a jar wont work

### Pack Version

Version: B Limitless-7-035.1

### To Reproduce

1.i have most of the high lvl enchants on armor and tools just not mending and try to make the cow in the jar it take anvils i wasted 20 anvils alot of iron on this

### Are you using OptiFine or Oculus?

- [x] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [x] Yes.
- [ ] No.

### Anything else to add?

i lost alot of iron b/c of this it wont give the anvil back i got video of the cow in the jar 
[crash-2024-01-09_14.47.21-client.txt](https://github.com/The-Nexus-Project/Limitless-7/files/13878621/crash-2024-01-09_14.47.21-client.txt)

https://medal.tv/games/minecraft/clips/1OfBnO9FO2QX6y/d1337G4mVf6v?invite=cr-MSxORk0sMTk2NjMzNTUs

**Comment by Gbergz** [comment]
Fixed in v0.36.0
