### ISSUE TITLE
[Issue]: Break Gameplay : duplicate redstone

### ISSUE THREAD

**Issue by Aydenss** [The-Nexus-Project/Limitless-7#72]
### What happened?

The **Raw Redstone Block** _(Regions Unexplored)_ is picked up in large quantities in a Nether biome and craftable with 4 **Redstone Dust** _(Minecraft)_

Crush Raw Redstone Block _(Regions Unexplored)_ with :
- **Crushing Macerator** _(Cyclic)_ = 4 Redstone + 6 (60%)
- **SAG Mill** _(Ender IO)_ = 8 Redstone + 1 (20%)
- **Crusher** _(Immersive Engineering)_ = 6 Redstone
- **Mechnanical Squeezer** _(IntegratedDynamics)_ = 12 Redstone + 2 (50%)
- **Squeezer** _(IntegratedDynamics)_ = 8 Redstone + 4 (50%)
- **Enrichment Chamber** _(Mekanism)_ = 12 Redstone

### Pack Version

Version: 0.35.1

### To Reproduce

1.  Mine the **Raw Redstone Block** _(Regions Unexplored)_ in the Nether or craft with 4 **Redstone Dust** _(Minecraft)_
2.  Crush in **Mechnanical Squeezer** _(IntegratedDynamics)_ = 12.5 Redstone
3.  You have just multiplied by 3 the amount of initial redstone
4.  Infinite loop, back to the First Step

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
While this is not a big issue, it can be looked into and fixed.

Thanks for report!

**Comment by Gbergz** [comment]
Fixed next update (v0.37.0), thanks for report!
