### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by gggamer6665** [The-Nexus-Project/Limitless-7#73]
### What happened?

A bug happened!

### Pack Version

Version: 

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Nothing is present in the report, open another one with info.
