### ISSUE TITLE
[Issue]: Crafting Thermal Series Rubber using Buckets from More buckets shows incorrect output

### ISSUE THREAD

**Issue by afielkris** [The-Nexus-Project/Limitless-7#74]
### What happened?

Just having the bucket in the crafting grid allows the user to craft rubber that way rather than the JEI way with dandelion and water or vines with water. It recognizes the liquid latex instead of it being recognized as just water. It also shows the Sal Ammoniac liquid and lets you craft it with just water.

https://i.imgur.com/9XrFEt0.png
https://i.imgur.com/BXuKqPi.png

### Pack Version

Version: 0.36.0

### To Reproduce

1. Fill a bucket from more buckets with water.
2. Insert it in a 2x2 or 3x3 crafting grid
3. will then be able to craft the rubber with just using water.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Fixed next update, thanks for report!
