### ISSUE TITLE
Unable to auto-craft any artifacts  

### ISSUE THREAD

**Issue by BigAngelUK** [The-Nexus-Project/Limitless-7#75]
### What happened?

Trying to auto-craft an umbrella (any artifacts) with Hostile Neural Networks . I have tried with a normal crafter and a gold crafter with refined storage.  I cant craft it manually as you cant scroll to get to anything not showing on the loot fabricator

### Pack Version

TNP unlimited  7

### To Reproduce

1. see above

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Artifacts are not craftable, they're found in loot chests.

**Comment by BigAngelUK** [comment]
yes they are with predictions on the hostile neural network if it isn't why did I spend 3 days searching for mimics to get it to basic

![2024-01-18_22 11 23 loot fabricator](https://github.com/The-Nexus-Project/Limitless-7/assets/52356723/ad5924d0-57ee-4e9f-9f25-dcf35f264537)

![2024-01-18_22 12 40  uses of mimic prediction](https://github.com/The-Nexus-Project/Limitless-7/assets/52356723/e5b57092-f2ce-4abd-ad12-a74c5088a5cc)

**Comment by Gbergz** [comment]
Well that's not native to the Artifacts mod, and is related to the Hostile Neural Networks mod. Should be reported to them.
