### ISSUE TITLE
[Issue]: Massive Lag [Single Player]

### ISSUE THREAD

**Issue by Gown-dono** [The-Nexus-Project/Limitless-7#78]
### What happened?

Every minute 'ms' suddenly goes up to 400-500 and there is a big fps drop(100-120 fps to 5 fps.). After a few seconds it goes back to 30-50 fps and then back to 120 fps.(occurs even if i do nothing.)

![Screenshot 2024-01-19 110244](https://github.com/The-Nexus-Project/Limitless-7/assets/71151655/5ff06eb6-13df-41d1-bb6f-d376dddbe990)

### Pack Version

Version: 0.36.0

### To Reproduce

1.It happens by itself.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Run a spark profiler when its lagging to see whats causing it.
Usage: https://spark.lucko.me/docs/Command-Usage

**Comment by Gown-dono** [comment]
Here: https://spark.lucko.me/K25FsmDUmH

**Comment by Gbergz** [comment]
So, you have an Ancient Compass somewhere in your storage space. Or just in your inventory.

Take it out. And delete it. Toss it into lava. Should improve your tps by a lot.

**Comment by Gbergz** [comment]
It's stuck looking for a structure, bringing your tps down with it. It's a known issue.

**Comment by Gown-dono** [comment]
There are still delays in the world, but it's much better than before. Thank you.
