### ISSUE TITLE
[Issue]: JEI not showing items

### ISSUE THREAD

**Issue by AnzuiVR** [The-Nexus-Project/Limitless-7#79]
### What happened?

JEI doesn't show any items on the right side of the screen unless I first type anything into the search bar. I could not find anything regarding the mod with recent versions of Minecraft (1.20.0+) so is it a setting within the mod-pack?

### Pack Version

Version: 1.20.1
Modpack Version: 0.36.0

### To Reproduce

- open inventory, no items shown in JEI
- type anything into search bar, items appear in JEI
![Screenshot 2024-01-21 002403](https://github.com/The-Nexus-Project/Limitless-7/assets/157267466/294ffdcd-b962-4b38-b6df-0f898ab1f46f)
![Screenshot 2024-01-21 002410](https://github.com/The-Nexus-Project/Limitless-7/assets/157267466/fd5462f7-2620-4f8a-a151-f794f5961634)

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Normal and working as expected.

To "bring it back" just write any valid result into the JEI search bar and voilà!
You can also just put a space into the search bar and it'll display like "normal".

Or.. alternatively if you don't like this feature at all you can fully disable it in Options -> Embeddium Settings then under the Performance tab.

Hopefully that helped!
