### ISSUE TITLE
[Issue]: Quest refined storage silicon unreachable

### ISSUE THREAD

**Issue by Fuzsoo** [The-Nexus-Project/Limitless-7#8]
### What happened?

The quest from refined storage where you need a silicon requires a silicon from the mod itself but the silicon you can craft is from ender io.

### Pack Version

Version: 0.20.1

### To Reproduce

-

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
I'll adjust this next update, thanks for noticing!
