### ISSUE TITLE
[Issue]: Sky Glitch

### ISSUE THREAD

**Issue by DarkHerox03** [The-Nexus-Project/Limitless-7#84]
### What happened?

A bug happened! Sky has a gray line that divides between the gray and normal color of the sky.
![2024-02-07_17 14 06](https://github.com/The-Nexus-Project/Limitless-7/assets/159381492/d273a505-cdbf-45cb-b9d1-8d31a55a6b12)

### Pack Version

Version: 0.37.1

### To Reproduce

1. Always is there even after relogging in. Even at night it shows up.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
you must've enabled some setting in Embeddium Settings
this doesnt happen by default.

**Comment by DarkHerox03** [comment]
i never changed anything

**Comment by Gbergz** [comment]
Reinstall the modpack, see if it changes anything.

**Comment by DarkHerox03** [comment]
alright
