### ISSUE TITLE
[Issue]: creative jet pack quest broken

### ISSUE THREAD

**Issue by platinum831** [The-Nexus-Project/Limitless-7#85]
### What happened?

pulled iron jet packs steel jet pack out of basic energy cube and it completed the create jet pack quest

### Pack Version

Version: 1.20.1/0.38.0

### To Reproduce

1.place steel jet pack in energy cube 
2.pull it out

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Thanks for report I'll investigate.

**Comment by Gbergz** [comment]
Will be fixed next update. (v0.39.0).
