### ISSUE TITLE
[Issue]: issue with JEI

### ISSUE THREAD

**Issue by Minecraftmodsappreciator** [The-Nexus-Project/Limitless-7#86]
### What happened?

Jei doesn´t appear 

### Pack Version

Version: 1.20.1 0.38 beta

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
![Uploading bild.png…]()
