### ISSUE TITLE
Server Crashes due to an Endless generating Loop

### ISSUE THREAD

**Issue by Golden-Fur** [The-Nexus-Project/Limitless-7#89]
We set up a server from Nitrado for this Modpack with Version 0.40.0
Everytime I want to go exploring the server crashes. (log attached)
We read through the log already, saying that structures want to spawn on the same location with none of them having a priority of spawning, causing the server to go into an endless loop and crash.
More strangely is, that it only seems to appear if **I** go exploring.
The others haven't had problems with it so far.
We already tried to generate a new world with a new seed, but this didn't help either.

Beg for help.
[latest(1).log](https://github.com/The-Nexus-Project/Limitless-7/files/14433340/latest.1.log)

**Comment by Golden-Fur** [comment]
I'll try to update the forge version.
Also no, we haven't modified the pack in any way.

**Comment by Golden-Fur** [comment]
Well... The server doesn't recognize the new java file...
I'll try with a friend to fix it, but help is appreciated"^^
![grafik](https://github.com/The-Nexus-Project/Limitless-7/assets/129628131/e0a6e12d-5fe0-4aec-a459-db525ed3fea1)

**Comment by Golden-Fur** [comment]
Well, after a lot of time and switching to Bisect-Hosting for the server it turns out, that the fault was indeed the Forge Version.
Thank you for your help.

**Comment by Gbergz** [comment]
No problems!
