### ISSUE TITLE
Windows defender flags a mod

### ISSUE THREAD

**Issue by JayJay1748** [The-Nexus-Project/Limitless-7#91]
### What happened?

Windows defender flagged apotheotic_additions1.5.jar.MchHOy as a Trojan:Script/Wacatac.B!ml and it happened after installing the modpack even without running it.

### Pack Version

Version: 0.41.0

### To Reproduce

1.Just downloading the modpack did it

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
[replied in discord.](https://github.com/The-Nexus-Project/Limitless-7/issues/90)
