### ISSUE TITLE
[Issue]: JEI will not display

### ISSUE THREAD

**Issue by Noathon** [The-Nexus-Project/Limitless-7#92]
### What happened?

No recipes show up at the side of the screen. The shortcut to show/hide JEI still works, as when I press this the search bar disappears. Despite this, I can still click on where the recipes would be, despite not being able to see them.

### Pack Version

Version: 0.41.1

### To Reproduce

1. Opened a new world. Any new world I open does not have JEI recipes display.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
![pic](https://github.com/The-Nexus-Project/Limitless-7/assets/26634554/dee096a8-f751-45a7-804d-615aac3fd1e7)
