### ISSUE TITLE
[Issue]: Server will not launch after updating to 1.0.0

### ISSUE THREAD

**Issue by cauliflower69** [The-Nexus-Project/Limitless-7#94]
### What happened?

After updating the server crashes. I have also tried loading in SP and the same error occurs with datapacks and then of you select safemode it throws an error for corrupt world. 

The world worked 100% fine on previous versions

### Pack Version

Version: 1.0.0

### To Reproduce

1. Load the world into a server or single player environment

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell

You will find both of the below files here https://requiemofapickaxe.com/modpack/

debug.log 

world.zip
```

### Anything else to add?

A fresh world does work fine but we were hoping to keep the world we have been playing on

**Comment by Gbergz** [comment]
1.0.0 is breaking as noted very clearly in the changelog, old worlds might not be compatible with it.
New world is recommended.
https://github.com/The-Nexus-Project/Limitless-7/blob/main/changelogs.md#v100

**Comment by cauliflower69** [comment]
Thanks for the reply, I had provided both the debug.log and the world.zip which are available here https://requiemofapickaxe.com/modpack/

**Comment by Gbergz** [comment]
Send them as files here.

**Comment by cauliflower69** [comment]
https://requiemofapickaxe.com/modpack/debug.log

https://requiemofapickaxe.com/modpack/world.zip

**Comment by Gbergz** [comment]
Drag and drop the files here. The actual files not a website.
Or upload to https://gist.github.com/
