### ISSUE TITLE
[Issue]: Bug | Broken Recipe | Mob Grinding Utilities | XP Mould Blank

### ISSUE THREAD

**Issue by MuseOfWorlds** [The-Nexus-Project/Limitless-7#95]
### What happened?

The crafting recipe for the XP Mould Blank doesn't work.

### Pack Version

Version: 0.41.1

### To Reproduce

1. 8 Golden Nuggets
2. Put in a square around the outside of the 3x3 Crafting Grid
3. No output
Should output: XP Mould Blank from Mob Grinding Utilities

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

**Comment by Gbergz** [comment]
You need an XP bucket or similar from that mod in the middle. Currently JEI has issues displaying some fluid buckets.

**Comment by MuseOfWorlds** [comment]
> You need an XP bucket or similar from that mod in the middle. Currently JEI has issues displaying some fluid buckets.

That would do it, thank you.
