### ISSUE TITLE
[Issue]: Pumpjack Hole missing from JEI

### ISSUE THREAD

**Issue by nddragoon** [The-Nexus-Project/Limitless-7#98]
### What happened?

The pumpjack multiblock from the Create: Diesel Generators mod needs a block that has a recipe but isn't listed in JEI. This is technically an issue with the mod itself but the developer hasn't fixed it in weeks and it should probably be relatively simple to fix in the pack.
The block ID is `createdieselgenerators:pumpjack_hole` and the recipe id is `createdieselgenerators:crafting/pumpjack_hole`

### Pack Version

Version: 1.1.0

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Pretty sure only the mod developer can add their items to JEI if they're missing. 

Not much I can do myself.

**Comment by Gbergz** [comment]
Never mind, with KubeJS i believe this is possible. Will update here whenever I can.

**Comment by Gbergz** [comment]
Fixed in 1.2.0
