### ISSUE TITLE
[Issue]: Eidolon Crucible

### ISSUE THREAD

**Issue by Legorfyr** [The-Nexus-Project/Limitless-7#99]
### What happened?

The Crucible from Eidolon refuses to take any ingredient to craft anything. The crucible is heated, has water and it's bubbling, yet items stay on the bottom of the cauldron and are not getting dissolved.

### Pack Version

Version: 1.10

### To Reproduce

1. Netherrack, light it, place crucible on top, pour water in, wait for the bubbles.
2. Throw in 2 redstone and a soul shard (first step to make arcane gold)
3. Watch as the items stay in the cauldron, not getting dissolved.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
https://github.com/Alexthw46/Eidolon-Repraised/issues

**Comment by Legorfyr** [comment]
Ok, reported it there, in the meantime, is it possible to downgrade the mod to eidolon_repraised-1.20.1-0.3.8.1 ?
Because without the crucible working, it locks 70% of the mod.

**Comment by Gbergz** [comment]
Downgraded in 1.2.0
